### ISSUE TITLE
Error loading PyV8 (ST3 + Ubuntu 14.04)

### ISSUE THREAD

**Issue by janklimo** [Slava/tern-meteor#27]
Despite having manually installed PyV8, the loader tries to load data from remote. Any idea how to fix it?

```python
plugins loaded
PyV8: Creating new thread
TernJS: Creating thread
Syncing project empty
Starting TernJS server for empty with 1 libs and 0 files
TernJS: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
TernJS: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-linux64-p3.zip
Package Control: Skipping automatic upgrade, last run at 2014-12-11 14:31:55, next run at 2014-12-11 15:31:55 or after
Exception in thread Thread-35:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 1142, in run
  File "/home/jan/.config/sublime-text-3/Installed Packages/TernJS.sublime-package/ternjs/pyv8loader.py", line 268, in run
    return self.trigger('error', exit_code=self.thread.exit_code, progress=self)
  File "/home/jan/.config/sublime-text-3/Installed Packages/TernJS.sublime-package/ternjs/pyv8loader.py", line 287, in trigger
    c(*args, **kwargs)
TypeError: on_error() got an unexpected keyword argument 'progress'
```

**Comment by Slava** [comment]
Hey guys, I just released my own package that bundles everything nicely and has no issues with PyV8: https://github.com/Slava/tern-meteor-sublime
