### ISSUE TITLE
Install with YouCompleteMe

### ISSUE THREAD

**Issue by ghost** [Slava/tern-meteor#40]
Hi,

I tried to copy the raw content of `meteor.js` to `/plugin/` folder of YouCompleteMe's Tern folder. When starting up the server I got the error message:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'tern/lib/infer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/erikhallstrom/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/tern/plugin/meteor.js:3:16
    at Object.<anonymous> (/Users/erikhallstrom/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/tern/plugin/meteor.js:7:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
/var/folders/rg/l2gcwfl55sldgtv142jbmn3h0000gn/T/ycm_temp/tern_49788_stderr.log (END)
```

However by changing `return mod(require("tern/lib/infer"), require("tern/lib/tern"), require);` in the first row to `../lib/infer` it worked! Why is this?

**Comment by Slava** [comment]
It could be the case that YouCompleteMe just uses a different version and/or fork of Tern.
